CREATE TABLE BOARD (
  BOARD_NUMBER NUMBER(38,0) DEFAULT 1 NOT NULL ENABLE,
  BOARD_WRITER VARCHAR2(20) NOT NULL ENABLE,
  BOARD_TITLE VARCHAR2(50) NOT NULL ENABLE,
  BOARD_CONTENT CLOB NOT NULL ENABLE,
  BOARD_PW VARCHAR2(20) NOT NULL ENABLE,
  BOARD_REGDATE TIMESTAMP (6) NOT NULL ENABLE,
  BOARD_READCOUNT NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE,
  BOARD_GROUP NUMBER(38,0) DEFAULT 1 NOT NULL ENABLE,
  BOARD_STEP NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE,
  BOARD_LEVEL NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE,
  PRIMARY KEY (BOARD_NUMBER)
);

CREATE SEQUENCE board_number_seq
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER board_number_trg
BEFORE INSERT ON board
FOR EACH ROW
BEGIN
  SELECT board_number_seq.NEXTVAL
  INTO :new.board_number
  FROM dual;
END;
/