CREATE TABLE MEMBER (
  MEMBER_ID VARCHAR2(20) NOT NULL ENABLE,
  MEMBER_PW VARCHAR2(20) NOT NULL ENABLE,
  MEMBER_NAME VARCHAR2(30) NOT NULL ENABLE,
  MEMBER_TEL VARCHAR2(20) NOT NULL ENABLE,
  MEMBER_EMAIL VARCHAR2(50) NOT NULL ENABLE,
  MEMBER_ZIPCODE VARCHAR2(10) NOT NULL ENABLE,
  MEMBER_ADDR VARCHAR2(100) NOT NULL ENABLE,
  MEMBER_ADDR2 VARCHAR2(100) NOT NULL ENABLE,
  MEMBER_REGDATE TIMESTAMP (6) NOT NULL ENABLE,
  PRIMARY KEY (MEMBER_ID)
);

CREATE SEQUENCE member_id_seq
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER member_id_trg
BEFORE INSERT ON member
FOR EACH ROW
BEGIN
  SELECT member_id_seq.NEXTVAL
  INTO :new.member_id
  FROM dual;
END;
/