CREATE TABLE "JUNGHO"."MEMBER"
   (	"MEMBER_ID" VARCHAR2(20) NOT NULL ENABLE,
	"MEMBER_PW" VARCHAR2(20) NOT NULL ENABLE,
	"MEMBER_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"MEMBER_TEL" VARCHAR2(20) NOT NULL ENABLE,
	"MEMBER_EMAIL" VARCHAR2(50) NOT NULL ENABLE,
	"MEMBER_ZIPCODE" VARCHAR2(10) NOT NULL ENABLE,
	"MEMBER_ADDR" VARCHAR2(100) NOT NULL ENABLE,
	"MEMBER_ADDR2" VARCHAR2(100) NOT NULL ENABLE,
	"MEMBER_REGDATE" TIMESTAMP (6) NOT NULL ENABLE,
	 PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE UNIQUE INDEX "JUNGHO"."SYS_C007024" ON "JUNGHO"."MEMBER" ("MEMBER_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;