CREATE TABLE NOTICE (
  NOTICE_NUMBER NUMBER(38,0) DEFAULT 1,
  NOTICE_READCOUNT NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE,
  NOTICE_WRITER VARCHAR2(20) NOT NULL ENABLE,
  NOTICE_TITLE VARCHAR2(100) NOT NULL ENABLE,
  NOTICE_CONTENT CLOB NOT NULL ENABLE,
  NOTICE_REGDATE TIMESTAMP (6) NOT NULL ENABLE,
  NOTICE_STEP NUMBER(38,0) NOT NULL ENABLE,
  NOTICE_LEVER NUMBER(38,0) NOT NULL ENABLE,
  NOTICE_GROUP NUMBER(38,0) DEFAULT 1 NOT NULL ENABLE,
  PRIMARY KEY (NOTICE_NUMBER)
);

CREATE SEQUENCE notice_number_seq
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER notice_number_trg
BEFORE INSERT ON notice
FOR EACH ROW
BEGIN
  SELECT notice_number_seq.NEXTVAL
  INTO :new.notice_number
  FROM dual;
END;
/

UPDATE NOTICE SET notice_writer = 'OP_KIM' WHERE notice_number = 1;
UPDATE NOTICE SET notice_writer = 'OP_LEE' WHERE notice_number = 2;
UPDATE NOTICE SET notice_writer = 'OP_PARK' WHERE notice_number = 3;
UPDATE NOTICE SET notice_writer = 'OP_KIM' WHERE notice_number = 4;
UPDATE NOTICE SET notice_writer = 'OP_MUN' WHERE notice_number = 5;
UPDATE NOTICE SET notice_writer = 'OP_SEO' WHERE notice_number = 6;
UPDATE NOTICE SET notice_writer = 'OP_HONG' WHERE notice_number = 7;
UPDATE NOTICE SET notice_writer = 'OP_KIM' WHERE notice_number = 8;
UPDATE NOTICE SET notice_writer = 'OP_LEE' WHERE notice_number = 9;
UPDATE NOTICE SET notice_writer = 'OP_PARK' WHERE notice_number = 10;
UPDATE NOTICE SET notice_writer = 'OP_KIM' WHERE notice_number = 11;
UPDATE NOTICE SET notice_writer = 'OP_MUN' WHERE notice_number = 12;
UPDATE NOTICE SET notice_writer = 'OP_SEO' WHERE notice_number = 13;