CREATE TABLE "JUNGHO"."NOTICE"
   (	"NOTICE_NUMBER" NUMBER(38,0) DEFAULT 1,
	"NOTICE_READCOUNT" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE,
	"NOTICE_WRITER" VARCHAR2(20) NOT NULL ENABLE,
	"NOTICE_TITLE" VARCHAR2(100) NOT NULL ENABLE,
	"NOTICE_CONTENT" CLOB NOT NULL ENABLE,
	"NOTICE_REGDATE" TIMESTAMP (6) NOT NULL ENABLE,
	"NOTICE_FIX" CHAR(1) NOT NULL ENABLE,
	"NOTICE_STEP" NUMBER(38,0) NOT NULL ENABLE,
	"NOTICE_LEVER" NUMBER(38,0) NOT NULL ENABLE,
	"NOTICE_GROUP" NUMBER(38,0) DEFAULT 1 NOT NULL ENABLE,
	 PRIMARY KEY ("NOTICE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
 LOB ("NOTICE_CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "JUNGHO"."SYS_C007032" ON "JUNGHO"."NOTICE" ("NOTICE_NUMBER")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "JUNGHO"."SYS_IL0000020068C00005$$" ON "JUNGHO"."NOTICE" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
  PARALLEL (DEGREE 0 INSTANCES 0) ;