CREATE TABLE "JUNGHO"."QNA"
   (	"QNA_NUMBER" NUMBER(38,0) DEFAULT 1 NOT NULL ENABLE,
	"QNA_READCOUNT" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE,
	"QNA_GROUP" NUMBER(38,0) DEFAULT 1 NOT NULL ENABLE,
	"QNA_STEP" NUMBER(*,0) NOT NULL ENABLE,
	"QNA_LEVEL" NUMBER(*,0) NOT NULL ENABLE,
	"QNA_WRITER" VARCHAR2(20) NOT NULL ENABLE,
	"QNA_PW" VARCHAR2(20) NOT NULL ENABLE,
	"QNA_TITLE" VARCHAR2(100) NOT NULL ENABLE,
	"QNA_CONTENT" CLOB NOT NULL ENABLE,
	"QNA_REGDATE" TIMESTAMP (6) NOT NULL ENABLE,
	 PRIMARY KEY ("QNA_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
 LOB ("QNA_CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "JUNGHO"."SYS_C007043" ON "JUNGHO"."QNA" ("QNA_NUMBER")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "JUNGHO"."SYS_IL0000020072C00009$$" ON "JUNGHO"."QNA" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
  PARALLEL (DEGREE 0 INSTANCES 0) ;